const assert=require('node:assert/strict'),path=require('node:path');
const KEY='customerservice-learning-v1';
async function go(p,h){await p.evaluate(h=>location.hash=h,h);await p.waitForTimeout(35);}
async function state(p){return p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);}
async function reset(p){await go(p,'home');await p.locator('#reset').click();await p.locator('#confirm-reset').click();}
async function answer(p,q,correct=true){const f=p.locator(`[data-quiz="${q.id}"]`);if(q.type==='match'){for(let i=0;i<q.rows.length;i++)await f.locator('select').nth(i).selectOption(String(correct?q.answer[i]:(q.answer[i]+1)%q.options.length));}else if(q.type==='order'){const ids=correct?q.answer:[...q.answer].reverse();for(let target=0;target<ids.length;target++){let count=0;while(true){const current=await f.locator('[data-item]').evaluateAll(es=>es.map(e=>Number(e.dataset.item)));if(current.indexOf(ids[target])===target)break;await f.locator(`[data-item="${ids[target]}"] [data-move="-1"]`).click();if(++count>20)throw Error('Order stuck');}}}else await f.locator(`input[value="${correct?q.answer:(q.answer+1)%q.options.length}"]`).check();await f.locator('button[type=submit]').click();}
exports.surfaces=async(p,out)=>{const errors=[],overflow=[];p.on('pageerror',e=>errors.push(String(e)));let count=0;for(const width of [320,375,390,430,768,1280,1440]){await p.setViewportSize({width,height:900});for(const route of ['home','course','how','about','progress',...Array.from({length:34},(_,i)=>'lesson/'+i)]){await go(p,route);const dim=await p.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth,h1:document.querySelectorAll('main h1').length}));if(dim.scroll>width+1||dim.h1!==1)overflow.push({width,route,...dim});count++;}await go(p,'course');await p.locator('[data-lesson="lesson-31"]').click();const modal=await p.locator('#coming').evaluate(d=>({width:d.getBoundingClientRect().width,viewport:innerWidth,height:d.getBoundingClientRect().height,available:innerHeight}));assert.ok(modal.width<=width&&modal.height<=modal.available);await p.keyboard.press('Escape');if(width===390||width===1440){await go(p,'home');await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:path.join(out,`cs-home-${width}.png`),fullPage:true});await go(p,'lesson/17');await p.screenshot({path:path.join(out,`cs-lesson-${width}.png`),fullPage:true});}}
 assert.deepEqual(overflow,[]);assert.deepEqual(errors,[]);return {views:count,widths:7,overflow,consoleErrors:errors};};
exports.controls=async(p)=>{await reset(p);await p.setViewportSize({width:390,height:844});await p.locator('#menu').click();assert.equal(await p.locator('#menu').getAttribute('aria-expanded'),'true');await p.locator('#primary-nav a[href="#course"]').click();assert.equal(await p.locator('#menu').getAttribute('aria-expanded'),'false');for(let n=2;n<=31;n++){await p.locator(`[data-lesson="lesson-${String(n).padStart(2,'0')}"]`).click();assert.ok(await p.locator('#coming').isVisible());assert.match(await p.locator('#coming-lesson').innerText(),new RegExp('Lesson '+String(n).padStart(2,'0')));await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.querySelector('#coming').contains(document.activeElement)),true);await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.dataset.lesson),'lesson-'+String(n).padStart(2,'0'));}
 await p.locator('[data-lesson="lesson-02"]').click();await p.locator('#available').click();assert.match(p.url(),/#lesson\/0/);await go(p,'course');await p.locator('[data-lesson="lesson-03"]').click();await p.locator('#back-course').click();assert.equal(await p.locator('#coming').isVisible(),false);
 await go(p,'home');for(let n=0;n<7;n++){await p.locator('#next-scenario').click();}await go(p,'lesson/28');await p.locator('[data-memory="0"]').click();assert.equal(await p.locator('[data-memory="0"] .answer').isVisible(),true);await p.locator('[data-memory="0"]').click();assert.equal(await p.locator('[data-memory="0"] .answer').isVisible(),false);await go(p,'lesson/27');await p.locator('.revision summary').first().click();assert.equal(await p.locator('.revision details').first().getAttribute('open'),'');
 await go(p,'lesson/30');await p.locator('#reflection-text').fill('A clear explanation helped me understand.');await p.locator('#reflection button[type=submit],#reflection button:not([type])').first().click();assert.deepEqual((await state(p)).reflections,{});await p.locator('#save-reflection').check();await p.locator('#reflection button:not([type])').click();assert.equal((await state(p)).reflections['30'],'A clear explanation helped me understand.');await p.reload();assert.equal(await p.locator('#reflection-text').inputValue(),'A clear explanation helped me understand.');await p.locator('#clear-reflection').click();assert.deepEqual((await state(p)).reflections,{});
 await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');await p.emulateMedia({reducedMotion:'no-preference'});await p.setViewportSize({width:1280,height:900});await reset(p);return {comingSoonButtons:30,modalFocusEscape:'passed',menu:'passed',memoryCards:'passed',revision:'passed',optionalReflectionSave:'passed',reducedMotion:'passed'};};
exports.feedback=async(p)=>{await go(p,'lesson/1');await p.locator('#mark-section').click();assert.match(await p.locator('#mark-feedback').innerText(),/still some practice/);const q=await p.evaluate(()=>ACTIVITIES.find(q=>q.id==='support'));for(let i=0;i<2;i++){await answer(p,q,false);assert.match(await p.locator('[data-quiz="support"] .feedback').innerText(),/Not quite/);}await answer(p,q);assert.match(await p.locator('[data-quiz="support"] .feedback').innerText(),/Good choice/);await p.locator('#mark-section').click();await p.reload();assert.ok((await state(p)).completed.includes(1));await go(p,'lesson/2');const role=await p.evaluate(()=>ACTIVITIES.find(q=>q.id==='role'));for(let i=0;i<3;i++)await answer(p,role,false);assert.match(await p.locator('[data-quiz="role"] .feedback').innerText(),/The answer is/);await p.locator('[data-quiz="role"]').getByText('Practise this again',{exact:true}).click();await answer(p,role);await go(p,'progress');assert.equal(await p.locator('[data-quiz]').count(),0);await reset(p);await go(p,'lesson/33');await p.locator('#mark-section').click();assert.match(await p.locator('#mark-feedback').innerText(),/earlier sections/);return {hints:'passed',retryReveal:'passed',progressGate:'passed',persistence:'passed',errorReview:'passed',completionGate:'passed'};};
exports.sections=async(p,from,to)=>{let total=0;for(let n=from;n<to;n++){await go(p,'lesson/'+n);const qs=await p.evaluate(n=>ACTIVITIES.filter(q=>q.step===n),n);for(const q of qs){await answer(p,q);assert.match(await p.locator(`[data-quiz="${q.id}"] .feedback`).innerText(),/Good choice/);total++;}if(await p.locator('#mark-section').count()&&await p.locator('#mark-section').isEnabled())await p.locator('#mark-section').click();}assert.equal((await state(p)).completed.length,to);if(to===34){assert.match(await p.locator('main').innerText(),/Lesson 01 Complete/i);await p.locator('#next-lesson').click();assert.ok(await p.locator('#coming').isVisible());await p.keyboard.press('Escape');await p.locator('#practice-again').click();assert.match(p.url(),/#lesson\/29/);await go(p,'course');assert.match(await p.locator('[data-lesson="lesson-01"]').innerText(),/Completed/);assert.equal(await p.locator('[role=progressbar]').getAttribute('aria-valuenow'),'100');}return {sections:to-from,totalCompleted:to,activities:total};};
exports.reset=reset;
